<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=gb2312"/>
<title>交通信号灯智能巡检系统</title>
<style>
html,body,table,td,div,p,h1,h2,h3,h4,span{margin:0px;padding:0px;font-size:14px;
border:none;color:#333;}
html,body{background:#fff;}
#head{width:100%;background:#205AA7;border-bottom:5px solid #D7D7D7;}
#title{padding:20px;color:#fff;font-family:黑体;font-size:30px;}
#exit{padding:20px;}
#exitBtn{width:80px;height:30px;}
#body{width:100%;border-bottom: 1px solid #D7D7D7;border-top:1px solid #fff;}
#navtd{width:180px;padding-bottom:40px;border-right:2px solid #666;}
#navtd a{display:block;width:100%;height:40px;line-height:40px;text-decoration:underline;
text-indent:20px;background:#ECECEC;color:#333;margin:0px 0px 1px 0px;}
#navtd a:hover{background:#A0A0A0;text-decoration:none;}
#navtd a.cur{background:#666;color:#fff;font-weight:bold;text-decoration:none;}
#foot{width:100%;text-align:center;padding-top:30px;padding-bottom:50px;font-family:黑体;
font-size:15px;color:#666;}
</style>
</head>
<body>
<table id="head" border="0" cellspacing="0"><tr>
<td nowrap id="title">交通信号灯智能巡检系统</td>
</tr></table>
<table id="body" border="0" cellspacing="0"><tr>
<td nowrap id="navtd" valign="top">