/*----------------------------------------------------------------------------
 *      Generated by FCARM FILE CONVERTER V1.32
 *----------------------------------------------------------------------------
 *      Name:    WEB.C
 *      Purpose: HTTP Web page, generated by the user.
 *      Note:    This is a generated file, do not modify !!!
 *----------------------------------------------------------------------------
 *      This code is part of the RealView Run-Time Library.
 *      Copyright (c) 2004-2009 KEIL - An ARM Company. All rights reserved. 
 *---------------------------------------------------------------------------*/

#include <Net_Config.h>

#define FILECNT   7

const U16 FileCnt = FILECNT;

/*---------------------------------------------------------------------------*/

const U8 index_htm[] = {
   "<script>location='main_page.cgi';</script>"
};


/*---------------------------------------------------------------------------*/

const U8 network_cgi[] = {
   "i pg_header.inc\r\n"
   "t <a href=\"/main_page.cgi\">基本信息</a>\r\n"
   "t <a href=\"/system.cgi\">系统管理</a>\r\n"
   "t <a href=\"/aplication_set.cgi\">应用设置</a>\r\n"
   "t <a class=\"cur\">IP设置</a>\r\n"
   "t </td><td valign=\"top\">\r\n"
   "t <style>\r\n"
   "t #m_table{margin:0px 0px 0px 20px;}\r\n"
   "t #m_table tr td{padding:5px 30px 5px 30px;background:#fff;}\r\n"
   "t #m_table tr td.ti{font-weight:bold;padding:20px 30px 5px 5px;}\r\n"
   "t #m_table tr td.val{background:#eee;}\r\n"
   "t #m_table tr td.desc{background:#ccc;}\r\n"
   "t #m_table tr td.btns{padding:20px 30px 20px 0px;}\r\n"
   "t #m_table tr td.btns input{width:80px;height:30px;}\r\n"
   "t </style>\r\n"
   "t <form name=\"cgi\" action=\"network.cgi\" method=\"get\" onsubmit=\"return frmsubmit();\">\r\n"
   "t <table id=\"m_table\" border=\"0\" cellspacing=\"1\">\r\n"
   "#t <tr><td nowrap class=\"ti\">自动获取IP</td><td nowrap>&nbsp;</td></tr>\r\n"
   "#c x 1 <tr><td nowrap class=\"desc\">当前DHCP状态</td><td nowrap class=\"val\">%s</td></tr>\r\n"
   "#t <tr><td nowrap class=\"desc\">启用DHCP</td><td nowrap class=\"val\">\r\n"
   "#t <input type=\"radio\" name=\"radio9\" value=\"yes\" id=\"rad1A\" >\r\n"
   "#t <label for=\"rad1A\" class=\"slab\">启用</label>\r\n"
   "#t <input type=\"radio\" name=\"radio9\" checked=\"checked\" value=\"no\" id=\"rad1B\""
   " >\r\n"
   "#t <label for=\"rad1B\" class=\"slab\">禁用</label></td></tr>\r\n"
   "t <tr><td nowrap class=\"ti\">本机IP设置</td><td nowrap>&nbsp;</td></tr>\r\n"
   "t <tr><td nowrap class=\"desc\">本机IP</td><td nowrap class=\"val\">\r\n"
   "c a i <input type=\"text\" name=\"ip\" value=\"%d.%d.%d.%d\" size=\"18\" maxlength=\"18\"></td></tr>\r\n"
   "t <tr><td nowrap class=\"desc\">子网掩码</td><td nowrap class=\"val\">\r\n"
   "c a m <input type=\"text\" name=\"msk\" value=\"%d.%d.%d.%d\" size=\"18\" maxlength=\"18\"></td></tr>\r\n"
   "t <tr><td nowrap class=\"desc\">本机网关</td><td nowrap class=\"val\">\r\n"
   "c a g <input type=\"text\" name=\"gw\" value=\"%d.%d.%d.%d\" size=\"18\" maxlength=\"18\"></td></tr>\r\n"
   "t <tr><td nowrap class=\"ti\">服务器IP设置</td><td nowrap>&nbsp;</td></tr>\r\n"
   "t <tr><td nowrap class=\"desc\">主服务器IP</td><td nowrap class=\"val\">\r\n"
   "c a s <input type=\"text\" name=\"sip\" value=\"%d.%d.%d.%d\" size=\"18\" maxlength=\"18\"></td></tr>\r\n"
   "t <tr><td nowrap class=\"desc\">主服务器端口</td><td nowrap class=\"val\">\r\n"
   "c a p <input type=\"text\" name=\"spt\" value=\"%d\" size=\"18\" maxlength=\"18\"></td></tr>\r\n"
   "t <tr><td nowrap class=\"desc\">从服务器IP</td><td nowrap class=\"val\">\r\n"
   "c a w <input type=\"text\" name=\"sww\" value=\"%d.%d.%d.%d\" size=\"18\" maxlength=\"18\"></td></tr>\r\n"
   "t <tr><td nowrap class=\"desc\">从服务器端口</td><td nowrap class=\"val\">\r\n"
   "c a x <input type=\"text\" name=\"swp\" value=\"%d\" size=\"18\" maxlength=\"18\"></td></tr>\r\n"
   "t <tr><td nowrap>&nbsp;</td><td nowrap class=\"btns\">\r\n"
   "t <input type=\"submit\" value=\"确定\" id=\"confirm\"/>\r\n"
   "t <input type=\"reset\" value=\"重置\"/></td></tr></table></form>\r\n"
   "t <script>function frmsubmit(){return confirm('确定修改IP设置?');}</script>\r\n"
   "i pg_footer.inc\r\n"
   ". End of script must be closed with period."
};


/*---------------------------------------------------------------------------*/

const U8 system_cgi[] = {
   "i pg_header.inc\r\n"
   "t <a href=\"/main_page.cgi\">基本信息</a>\r\n"
   "t <a class=\"cur\">系统管理</a>\r\n"
   "t <a href=\"/aplication_set.cgi\">应用设置</a>\r\n"
   "t <a href=\"/network.cgi\">IP设置</a>\r\n"
   "t </td><td valign=\"top\">\r\n"
   "t <style>\r\n"
   "t #m_table{margin:0px 0px 0px 20px;}\r\n"
   "t #m_table tr td{padding:5px 30px 5px 30px;background:#fff;}\r\n"
   "t #m_table tr td.ti{font-weight:bold;padding:20px 30px 5px 5px;}\r\n"
   "t #m_table tr td.zs{font-weight:bold;padding:20px 250px 5px 5px;}\r\n"
   "t #m_table tr td.val{background:#eee;}\r\n"
   "t #m_table tr td.desc{background:#ccc;}\r\n"
   "t #m_table tr td.btns{padding:20px 30px 20px 0px;}\r\n"
   "t #m_table tr td.btns input{width:80px;height:30px;}\r\n"
   "t </style>\r\n"
   "t <form name=\"cgi\" action=\"system.cgi\" method=\"get\" onsubmit=\"return frmsubmit();\">\r\n"
   "t <table id=\"m_table\" border=\"0\" cellspacing=\"1\">\r\n"
   "t <tr><td nowrap class=\"ti\">基本设置</td><td nowrap>&nbsp;</td></tr>\r\n"
   "t <tr><td nowrap class=\"desc\">恢复出厂设置</td><td nowrap class=\"val\">\r\n"
   "t <input type=\"radio\" name=\"radio1\"  value=\"yes\" id=\"rad1A\" >\r\n"
   "t <label for=\"rad1A\">是</label>\r\n"
   "t <input type=\"radio\" name=\"radio1\" checked=\"checked\" value=\"no\" id=\"rad1B\""
   " >\r\n"
   "t <label for=\"rad1B\">否</label>\r\n"
   "t </td></tr>\r\n"
   "t <tr><td nowrap class=\"desc\">重新学习信号机</td><td nowrap class=\"val\">\r\n"
   "t <input type=\"radio\" name=\"radio2\"  value=\"yes\" id=\"rad2A\" >\r\n"
   "t <label for=\"rad2A\" class=\"slab\">是</label>\r\n"
   "t <input type=\"radio\" name=\"radio2\" checked=\"checked\" value=\"no\" id=\"rad2B\""
   " >\r\n"
   "t <label for=\"rad2B\" class=\"slab\">否</label>\r\n"
   "t </td></tr>\r\n"
   "t <tr><td nowrap class=\"desc\">重启设备</td><td nowrap class=\"val\">\r\n"
   "t <input type=\"radio\" name=\"radio3\" value=\"yes\" id=\"rad3A\" >\r\n"
   "t <label for=\"rad3A\" class=\"slab\">是</label>\r\n"
   "t <input type=\"radio\" name=\"radio3\" checked=\"checked\" value=\"no\" id=\"rad3B\""
   " >\r\n"
   "t <label for=\"rad3B\" class=\"slab\">否</label>\r\n"
   "t </td></tr>\r\n"
   "t <tr><td nowrap class=\"ti\">通道组合设置(见**注)</td><td nowrap>&nbsp;</td></tr>\r\n"
   "t <tr><td nowrap class=\"desc\">组合1</td><td nowrap class=\"val\">\r\n"
   "c v a <input type=\"text\" name=\"combine_pas1\" value=\"%d\" size=\"9\" maxlength=9>\r\n"
   "t <input type=\"checkbox\" name=\"combbox\" value =\"comb_pas1\" ></td></tr>\r\n"
   "t <tr><td nowrap class=\"desc\">组合2</td><td nowrap class=\"val\">\r\n"
   "c v b <input type=\"text\" name=\"combine_pas2\" value=\"%d\" size=\"9\" maxlength=9>\r\n"
   "t <input type=\"checkbox\" name=\"combbox\" value =\"comb_pas2\" ></td></tr>\r\n"
   "t <tr><td nowrap class=\"desc\">组合3</td><td nowrap class=\"val\">\r\n"
   "c v c <input type=\"text\" name=\"combine_pas3\" value=\"%d\" size=\"9\" maxlength=9>\r\n"
   "t <input type=\"checkbox\" name=\"combbox\" value =\"comb_pas3\" ></td></tr>\r\n"
   "t <tr><td nowrap class=\"desc\">组合4</td><td nowrap class=\"val\">\r\n"
   "c v d <input type=\"text\" name=\"combine_pas4\" value=\"%d\" size=\"9\" maxlength=9>\r\n"
   "t <input type=\"checkbox\" name=\"combbox\" value =\"comb_pas4\" ></td></tr>\r\n"
   "#t <tr><td nowrap class=\"desc\">组合5</td><td nowrap class=\"val\">\r\n"
   "#c v e <input type=\"text\" name=\"combine_pas5\" value=\"%d\" size=\"9\" maxlength=9>\r\n"
   "#t <input type=\"checkbox\" name=\"combbox\" value =\"comb_pas5\" ></td></tr>\r\n"
   "#t <tr><td nowrap class=\"desc\">通道组合6</td><td nowrap class=\"val\">\r\n"
   "#c v f <input type=\"text\" name=\"combine_pas6\" value=\"%d\" size=\"9\" maxlength=9>\r\n"
   "#t <input type=\"checkbox\" name=\"combbox\" value =\"comb_pas6\" ></td></tr>\r\n"
   "t <tr><td nowrap class=\"ti\">定时重启设置</td><td nowrap>&nbsp;</td></tr>\r\n"
   "c g a <tr><td nowrap class=\"desc\">当前定时重启状态</td><td nowrap class=\"val\">%s</td></tr>\r\n"
   "t <tr><td nowrap class=\"desc\">定时重启</td><td nowrap class=\"val\">\r\n"
   "t <input type=\"radio\" name=\"radio4\"  value=\"yes\" id=\"rad4A\" >\r\n"
   "t <label for=\"rad4A\" class=\"slab\">启用</label>\r\n"
   "t <input type=\"radio\" name=\"radio4\" checked=\"checked\" value=\"no\" id=\"rad4B\""
   " >\r\n"
   "t <label for=\"rad4B\" class=\"slab\">禁用</label>\r\n"
   "t </td></tr>\r\n"
   "t <tr><td nowrap class=\"desc\">定时重启</td><td nowrap class=\"val\">\r\n"
   "t <select name=\"restart_hour\">\r\n"
   "c b 1 <option>00</option><option>01</option><option>02</option><option>03</option><option>04</option>\r\n"
   "c b 1 <option>05</option><option>06</option><option>07</option><option>08</option><option>09</option>\r\n"
   "c b 1 <option>10</option><option>11</option><option>12</option><option>13</option><option>14</option>\r\n"
   "c b 1 <option>15</option><option>16</option><option>17</option><option>18</option><option>19</option>\r\n"
   "c b 1 <option>20</option><option>21</option><option>22</option><option>23</option></select>\r\n"
   "t 时<select name=\"restart_minute\">\r\n"
   "c b 2 <option>00</option><option>01</option><option>02</option><option>03</option><option>04</option>\r\n"
   "c b 2 <option>05</option><option>06</option><option>07</option><option>08</option><option>09</option>\r\n"
   "c b 2 <option>10</option><option>11</option><option>12</option><option>13</option><option>14</option>\r\n"
   "c b 2 <option>15</option><option>16</option><option>17</option><option>18</option><option>19</option>\r\n"
   "c b 2 <option>20</option><option>21</option><option>22</option><option>23</option><option>24</option>\r\n"
   "c b 2 <option>25</option><option>26</option><option>27</option><option>28</option><option>29</option>\r\n"
   "c b 2 <option>30</option><option>31</option><option>32</option><option>33</option><option>34</option>\r\n"
   "c b 2 <option>35</option><option>36</option><option>37</option><option>38</option><option>39</option>\r\n"
   "c b 2 <option>40</option><option>41</option><option>42</option><option>43</option><option>44</option>\r\n"
   "c b 2 <option>45</option><option>46</option><option>47</option><option>48</option><option>49</option>\r\n"
   "c b 2 <option>50</option><option>51</option><option>52</option><option>53</option><option>54</option>\r\n"
   "c b 2 <option>55</option><option>56</option><option>57</option><option>58</option><option>59</option></select>\r\n"
   "t 分</td></tr>\r\n"
   "t <tr><td nowrap>&nbsp;</td><td nowrap class=\"btns\">\r\n"
   "t <input type=\"submit\" value=\"确定\" id=\"confirm\"/>\r\n"
   "t <input type=\"reset\" value=\"重置\"/>\r\n"
   "t </td></tr>\r\n"
   "t </table>\r\n"
   "t <b>&nbsp注：</b><br />\r\n"
   "t <b>&nbsp;&nbsp;&nbsp通道1=1;</b><br />\r\n"
   "t <b>&nbsp;&nbsp;&nbsp通道2=2;</b><br />\r\n"
   "t <b>&nbsp;&nbsp;&nbsp通道3=4;</b><br />\r\n"
   "t <b>&nbsp;&nbsp;&nbsp通道4=8;</b><br />\r\n"
   "t <b>&nbsp;&nbsp;&nbsp如通道1与通道4组合，则组合的值为:8+1=9;</b><br />\r\n"
   "t <b>&nbsp;&nbsp;&nbsp最大支持4个组合</b><br />\r\n"
   "t </form>\r\n"
   "t <script>function frmsubmit(){return confirm('确定执行系统管理?');}</script>\r\n"
   "i pg_footer.inc\r\n"
   ". End of script must be closed with period."
};


/*---------------------------------------------------------------------------*/

const U8 main_page_cgi[] = {
   "i pg_header.inc\r\n"
   "t <a class=\"cur\">基本信息</a>\r\n"
   "t <a href=\"/system.cgi\">系统管理</a>\r\n"
   "t <a href=\"/aplication_set.cgi\">应用设置</a>\r\n"
   "t <a href=\"/network.cgi\">IP设置</a>\r\n"
   "t </td><td valign=\"top\">\r\n"
   "t <style>\r\n"
   "t #m_table{margin:20px 0px 0px 20px;}\r\n"
   "t #m_table tr td{padding:5px 30px 5px 30px;}\r\n"
   "t #m_table tr td{background:#eee;}\r\n"
   "t #m_table tr td.desc{background:#ccc;}\r\n"
   "t </style>\r\n"
   "t <form name=\"cgi\" action=\"main_page.cgi\" >\r\n"
   "t <table id=\"m_table\" border=\"0\" cellspacing=\"1\">\r\n"
   "c d 1 <tr><td nowrap class=\"desc\">设备信息</td><td nowrap>%s</td></tr>\r\n"
   "c d 2 <tr><td nowrap class=\"desc\">设备地点</td><td nowrap>%s</td></tr>\r\n"
   "c d a <tr><td nowrap class=\"desc\">设备型号</td><td nowrap>%s</td></tr>\r\n"
   "c d 3 <tr><td nowrap class=\"desc\">软件版本号</td><td nowrap>%s</td></tr>\r\n"
   "c d 4 <tr><td nowrap class=\"desc\">MAC地址</td><td nowrap>%s-%s-%s-%s-%s-%s</td></tr>\r\n"
   "c d 5 <tr><td nowrap class=\"desc\">本机IP</td><td nowrap>%d.%d.%d.%d</td></tr>\r\n"
   "c d 6 <tr><td nowrap class=\"desc\">服务器IP</td><td nowrap>%d.%d.%d.%d</td></tr>\r\n"
   "c d 7 <tr><td nowrap class=\"desc\">服务器端口</td><td nowrap>%s</td></tr>\r\n"
   "c d 8 <tr><td nowrap class=\"desc\">交流电电压比</td><td nowrap>%.1f</td></tr>\r\n"
   "c d 9 <tr><td nowrap class=\"desc\">交流电压实时监测(F5刷新)</td><td nowrap>%d"
   " V</td></tr>\r\n"
   "c d b <tr><td nowrap class=\"desc\">是否学习</td><td nowrap>%s</td></tr>\r\n"
   "c d c <tr><td nowrap class=\"desc\">学习的有效通道(顺序:绿黄红)</td><td nowrap>%s</td></tr>\r\n"
   "c d e <tr><td nowrap class=\"desc\">学习的通道电流(顺序:绿黄红)</td><td nowrap>%d"
   " %d %d %d %d %d %d %d %d %d %d %d</td></tr>\r\n"
   "c d f <tr><td nowrap class=\"desc\">周期时长</td><td nowrap>%d s</td></tr>\r\n"
   "c d d <tr><td nowrap class=\"desc\">当前阶段表</td><td nowrap>%s%d%s%d%d%d%d%d%d%d%d"
   " 绿%ds</td></tr>\r\n"
   "t <tr><td nowrap>&nbsp;</td><td nowrap class=\"btns\">\r\n"
   "t <input type=\"submit\" value=\"刷新\" id=\"confirm\"/></td></tr></table></form>\r\n"
   "i pg_footer.inc\r\n"
   ". End of script must be closed with period."
};


/*---------------------------------------------------------------------------*/

const U8 pg_header_inc[] = {
   "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n"
   "<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n"
   "<head>\r\n"
   "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=gb2312\"/>\r\n"
   "<title>交通信号灯智能巡检系统</title>\r\n"
   "<style>\r\n"
   "html,body,table,td,div,p,h1,h2,h3,h4,span{margin:0px;padding:0px;font-size:14px;\r\n"
   "border:none;color:#333;}\r\n"
   "html,body{background:#fff;}\r\n"
   "#head{width:100%;background:#205AA7;border-bottom:5px solid #D7D7D7;}\r\n"
   "#title{padding:20px;color:#fff;font-family:黑体;font-size:30px;}\r\n"
   "#exit{padding:20px;}\r\n"
   "#exitBtn{width:80px;height:30px;}\r\n"
   "#body{width:100%;border-bottom: 1px solid #D7D7D7;border-top:1px solid #fff;}\r\n"
   "#navtd{width:180px;padding-bottom:40px;border-right:2px solid #666;}\r\n"
   "#navtd a{display:block;width:100%;height:40px;line-height:40px;text-decoration:underline;\r\n"
   "text-indent:20px;background:#ECECEC;color:#333;margin:0px 0px 1px 0px;}\r\n"
   "#navtd a:hover{background:#A0A0A0;text-decoration:none;}\r\n"
   "#navtd a.cur{background:#666;color:#fff;font-weight:bold;text-decoration:none;}\r\n"
   "#foot{width:100%;text-align:center;padding-top:30px;padding-bottom:50px;font-family:黑体;\r\n"
   "font-size:15px;color:#666;}\r\n"
   "</style>\r\n"
   "</head>\r\n"
   "<body>\r\n"
   "<table id=\"head\" border=\"0\" cellspacing=\"0\"><tr>\r\n"
   "<td nowrap id=\"title\">交通信号灯智能巡检系统</td>\r\n"
   "</tr></table>\r\n"
   "<table id=\"body\" border=\"0\" cellspacing=\"0\"><tr>\r\n"
   "<td nowrap id=\"navtd\" valign=\"top\">"
};


/*---------------------------------------------------------------------------*/

const U8 pg_footer_inc[] = {
   "<br/>&nbsp;\r\n"
   "</td></tr></table>\r\n"
   "<div id=\"foot\">同力永昌科贸有限公司版权所有</div>\r\n"
   "</body>\r\n"
   "</html>"
};


/*---------------------------------------------------------------------------*/

const U8 aplication_set_cgi[] = {
   "i pg_header.inc\r\n"
   "t <a href=\"/main_page.cgi\">基本信息</a>\r\n"
   "t <a href=\"/system.cgi\">系统管理</a>\r\n"
   "t <a class=\"cur\">应用设置</a>\r\n"
   "t <a href=\"/network.cgi\">IP设置</a>\r\n"
   "t </td><td valign=\"top\">\r\n"
   "t <style>\r\n"
   "t #m_table{margin:20px 0px 0px 20px;}\r\n"
   "t #m_table tr td{padding:5px 30px 5px 30px;background:#fff;}\r\n"
   "t #m_table tr td.ti{font-weight:bold;padding:20px 30px 5px 5px;}\r\n"
   "t #m_table tr td.val{background:#eee;}\r\n"
   "t #m_table tr td.desc{background:#ccc;}\r\n"
   "t #m_table tr td.fre{background:#66ff33;}\r\n"
   "t #m_table tr td.btns{padding:20px 30px 20px 0px;}\r\n"
   "t #m_table tr td.btns input{width:80px;height:30px;}\r\n"
   "t </style>\r\n"
   "t <form name=\"cgi\" action=\"aplication_set.cgi\" method=\"get\" onsubmit=\"return"
   " frmsubmit();\">\r\n"
   "t <table id=\"m_table\" border=\"0\" cellspacing=\"1\">\r\n"
   "t <tr><td nowrap class=\"desc\">交流电校准电压</td>\r\n"
   "t <td nowrap class=\"val\">\r\n"
   "c t a <input type=\"text\" name=\"turn_num\" value=\"%.0f\" size=\"9\" maxlength=9>V</td>\r\n"
   "t <td nowrap class=\"val\"><input type=\"checkbox\" name=\"appbox\" value =\"stand_vol\""
   " >更改</td></tr>\r\n"
   "#t <tr><td nowrap class=\"desc\">交流电电压比</td><td nowrap class=\"val\">\r\n"
   "#c t f <input type=\"text\" name=\"turn_num_lxb\" value=\"%.0f\" size=\"9\" maxlength=9></td>\r\n"
   "#t <td nowrap class=\"val\"><input type=\"checkbox\" name=\"appbox\" value =\"stand_tun\""
   " >更改</td></tr>\r\n"
   "t <tr><td nowrap class=\"desc\">蓄电池异常报警值</td><td nowrap class=\"val\">\r\n"
   "c t b <input type=\"text\" name=\"bat_min\" value=\"%d\" size=\"9\" maxlength=\"9\">分钟</td>\r\n"
   "t <td nowrap class=\"val\"><input type=\"checkbox\" name=\"appbox\" value =\"bat_alarm\""
   " >更改</td></tr>\r\n"
   "t <tr><td nowrap class=\"desc\">信号灯异常报警阀值</td><td nowrap class=\"val\">\r\n"
   "c t c <input type=\"text\" name=\"cur_min\" value=\"%d\" size=\"9\" maxlength=\"9\">%%</td>\r\n"
   "t <td nowrap class=\"val\"><input type=\"checkbox\" name=\"appbox\" value =\"lamp_alarm\""
   " >更改</td></tr>\r\n"
   "t <tr><td nowrap class=\"desc\">信号灯电流上报周期</br>交流电或绿冲上报周期</td>\r\n"
   "t <td nowrap class=\"val\">\r\n"
   "c t d <input type=\"text\" name=\"send_time\" value=\"%d\" size=\"9\" maxlength=\"9\">分钟</td>\r\n"
   "t <td nowrap class=\"val\"><input type=\"checkbox\" name=\"appbox\" value =\"lamp_current\""
   " >更改</td></tr>\r\n"
   "t <tr><td nowrap>&nbsp;</td><td nowrap class=\"btns\">\r\n"
   "t <input type=\"submit\" value=\"确定\" id=\"confirm\"/>\r\n"
   "t <input type=\"reset\" value=\"重置\"/></td></tr></table></form>\r\n"
   "t <script>function frmsubmit(){return confirm('确定更改应用设置?');}</script>\r\n"
   "i pg_footer.inc\r\n"
   ". End of script must be closed with period."
};


/*---------------------------------------------------------------------------*/

const struct http_file FileTab[FILECNT] = {
   { "index.htm", (U8 *)&index_htm, 42 },
   { "network.cgi", (U8 *)&network_cgi, 2761 },
   { "system.cgi", (U8 *)&system_cgi, 6190 },
   { "main_page.cgi", (U8 *)&main_page_cgi, 1906 },
   { "pg_header.inc", (U8 *)&pg_header_inc, 1426 },
   { "pg_footer.inc", (U8 *)&pg_footer_inc, 100 },
   { "aplication_set.cgi", (U8 *)&aplication_set_cgi, 2394 },
};


/*----------------------------------------------------------------------------
 * end of file
 *---------------------------------------------------------------------------*/
